// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class geniusyield : Exchange
{
    public geniusyield (object args = null): base(args) {}

    public async Task<object> privateGetMarkets (object parameters = null)
    {
        return await this.callAsync ("privateGetMarkets",parameters);
    }

    public async Task<object> privateGetTradingFees (object parameters = null)
    {
        return await this.callAsync ("privateGetTradingFees",parameters);
    }

}