<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class geniusyield extends \ccxt\async\Exchange {
    public function private_get_balances_address($params = array()) {
        return $this->request('balances/{address}', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function private_get_markets($params = array()) {
        return $this->request('markets', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function private_get_trading_fees($params = array()) {
        return $this->request('trading-fees', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function private_get_settings($params = array()) {
        return $this->request('settings', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function privateGetBalancesAddress($params = array()) {
        return $this->request('balances/{address}', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function privateGetMarkets($params = array()) {
        return $this->request('markets', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function privateGetTradingFees($params = array()) {
        return $this->request('trading-fees', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
    public function privateGetSettings($params = array()) {
        return $this->request('settings', 'private', 'GET', $params, null, null, array("cost" => 10));
    }
}
